# Generated by Django 3.2.7 on 2021-10-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images'),
        ),
    ]
