# Generated by Django 3.2.7 on 2021-10-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest',
            new_name='author',
        ),
    ]
